import type { AdminOrder } from '../../lib/db/orders';

const now = new Date('2026-02-26T12:00:00.000Z');

const isoHoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();

export const seedAdminOrders: AdminOrder[] = [
  {
    id: 'seed_order_001',
    displayOrderId: 'MV-1001',
    createdAt: isoHoursAgo(3),
    totalCents: 15400,
    amountTotalCents: 15400,
    amountSubtotalCents: 13200,
    amountShippingCents: 1200,
    amountTaxCents: 1000,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'olivia.martin@example.com',
    shippingName: 'Olivia Martin',
    customerName: 'Olivia Martin',
    shippingAddress: {
      name: 'Olivia Martin',
      line1: '118 Harbor Lane',
      line2: '',
      city: 'Annapolis',
      state: 'MD',
      postal_code: '21401',
      country: 'US',
      phone: '+1 410-555-0101',
    },
    cardLast4: '4242',
    cardBrand: 'visa',
    paymentMethodType: 'card',
    paymentMethodLabel: 'Visa ending in 4242',
    shippingCents: 1200,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: false,
    seenAt: null,
    items: [
      {
        productId: 'seed_prod_001',
        productName: 'Oyster Shell Ring Dish',
        quantity: 2,
        priceCents: 4200,
        imageUrl: 'https://picsum.photos/seed/demo-prod-1/300/300',
      },
      {
        productId: 'seed_prod_002',
        productName: 'Coastal Trinket Bowl',
        quantity: 1,
        priceCents: 4800,
        imageUrl: 'https://picsum.photos/seed/demo-prod-2/300/300',
      },
    ],
  },
  {
    id: 'seed_order_002',
    displayOrderId: 'MV-1002',
    createdAt: isoHoursAgo(8),
    totalCents: 9800,
    amountTotalCents: 9800,
    amountSubtotalCents: 8800,
    amountShippingCents: 0,
    amountTaxCents: 1000,
    amountDiscountCents: 1200,
    currency: 'usd',
    customerEmail: 'ethan.reed@example.com',
    shippingName: 'Ethan Reed',
    customerName: 'Ethan Reed',
    shippingAddress: {
      name: 'Ethan Reed',
      line1: '22 Riverwalk Dr',
      line2: 'Apt 4B',
      city: 'Wilmington',
      state: 'NC',
      postal_code: '28401',
      country: 'US',
      phone: '+1 910-555-0142',
    },
    shippingCents: 0,
    promoCode: 'COASTAL10',
    promoPercentOff: 10,
    promoFreeShipping: true,
    promoSource: 'promo_code',
    isSeen: false,
    seenAt: null,
    items: [
      {
        productId: 'seed_prod_003',
        productName: 'Pearl Accent Shell Tray',
        quantity: 1,
        priceCents: 8800,
        imageUrl: 'https://picsum.photos/seed/demo-prod-3/300/300',
      },
    ],
  },
  {
    id: 'seed_order_003',
    displayOrderId: 'MV-1003',
    createdAt: isoHoursAgo(11),
    totalCents: 12600,
    amountTotalCents: 12600,
    amountSubtotalCents: 10800,
    amountShippingCents: 900,
    amountTaxCents: 900,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'harper.lynch@example.com',
    shippingName: 'Harper Lynch',
    customerName: 'Harper Lynch',
    shippingAddress: {
      name: 'Harper Lynch',
      line1: '77 Seaside Ave',
      city: 'Charleston',
      state: 'SC',
      postal_code: '29401',
      country: 'US',
      phone: '+1 843-555-0178',
    },
    shippingCents: 900,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(10),
    items: [
      {
        productId: 'seed_prod_004',
        productName: 'Wedding Place Card Shell Set',
        quantity: 1,
        priceCents: 10800,
        imageUrl: 'https://picsum.photos/seed/demo-prod-4/300/300',
      },
    ],
  },
  {
    id: 'seed_order_004',
    displayOrderId: 'MV-1004',
    createdAt: isoHoursAgo(15),
    totalCents: 21400,
    amountTotalCents: 21400,
    amountSubtotalCents: 18800,
    amountShippingCents: 1600,
    amountTaxCents: 1000,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'amelia.taylor@example.com',
    shippingName: 'Amelia Taylor',
    customerName: 'Amelia Taylor',
    shippingAddress: {
      name: 'Amelia Taylor',
      line1: '9 Sunrise Point',
      city: 'Savannah',
      state: 'GA',
      postal_code: '31401',
      country: 'US',
      phone: '+1 912-555-0199',
    },
    shippingCents: 1600,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(14),
    items: [
      {
        productId: 'seed_prod_005',
        productName: 'Bridal Party Shell Gift Box',
        quantity: 2,
        priceCents: 9400,
        imageUrl: 'https://picsum.photos/seed/demo-prod-5/300/300',
      },
    ],
  },
  {
    id: 'seed_order_005',
    displayOrderId: 'MV-1005',
    createdAt: isoHoursAgo(20),
    totalCents: 7600,
    amountTotalCents: 7600,
    amountSubtotalCents: 6600,
    amountShippingCents: 600,
    amountTaxCents: 400,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'noah.hayes@example.com',
    shippingName: 'Noah Hayes',
    customerName: 'Noah Hayes',
    shippingAddress: {
      name: 'Noah Hayes',
      line1: '1402 Bayview Ct',
      city: 'Tampa',
      state: 'FL',
      postal_code: '33602',
      country: 'US',
      phone: '+1 813-555-0110',
    },
    shippingCents: 600,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(18),
    items: [
      {
        productId: 'seed_prod_006',
        productName: 'Mini Oyster Ornament',
        quantity: 3,
        priceCents: 2200,
        imageUrl: 'https://picsum.photos/seed/demo-prod-6/300/300',
      },
    ],
  },
  {
    id: 'seed_order_006',
    displayOrderId: 'MV-1006',
    createdAt: isoHoursAgo(24),
    totalCents: 14500,
    amountTotalCents: 14500,
    amountSubtotalCents: 12900,
    amountShippingCents: 1000,
    amountTaxCents: 600,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'ava.king@example.com',
    shippingName: 'Ava King',
    customerName: 'Ava King',
    shippingAddress: {
      name: 'Ava King',
      line1: '19 Pelican Way',
      city: 'Newport',
      state: 'RI',
      postal_code: '02840',
      country: 'US',
      phone: '+1 401-555-0107',
    },
    shippingCents: 1000,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(22),
    items: [
      {
        productId: 'seed_prod_001',
        productName: 'Oyster Shell Ring Dish',
        quantity: 1,
        priceCents: 4200,
      },
      {
        productId: 'seed_prod_007',
        productName: 'Signature Shell Keepsake',
        quantity: 1,
        priceCents: 8700,
      },
    ],
  },
  {
    id: 'seed_order_007',
    displayOrderId: 'MV-1007',
    createdAt: isoHoursAgo(28),
    totalCents: 6100,
    amountTotalCents: 6100,
    amountSubtotalCents: 5200,
    amountShippingCents: 500,
    amountTaxCents: 400,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'liam.green@example.com',
    shippingName: 'Liam Green',
    customerName: 'Liam Green',
    shippingAddress: {
      name: 'Liam Green',
      line1: '8 Driftwood Ln',
      city: 'Mobile',
      state: 'AL',
      postal_code: '36602',
      country: 'US',
      phone: '+1 251-555-0155',
    },
    shippingCents: 500,
    promoCode: 'WELCOME5',
    promoPercentOff: 5,
    promoFreeShipping: false,
    promoSource: 'promo_code',
    isSeen: true,
    seenAt: isoHoursAgo(27),
    items: [
      {
        productId: 'seed_prod_006',
        productName: 'Mini Oyster Ornament',
        quantity: 2,
        priceCents: 2600,
      },
    ],
  },
  {
    id: 'seed_order_008',
    displayOrderId: 'MV-1008',
    createdAt: isoHoursAgo(34),
    totalCents: 18900,
    amountTotalCents: 18900,
    amountSubtotalCents: 17200,
    amountShippingCents: 1100,
    amountTaxCents: 600,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'mia.bennett@example.com',
    shippingName: 'Mia Bennett',
    customerName: 'Mia Bennett',
    shippingAddress: {
      name: 'Mia Bennett',
      line1: '404 Shoreline Blvd',
      city: 'Galveston',
      state: 'TX',
      postal_code: '77550',
      country: 'US',
      phone: '+1 409-555-0119',
    },
    shippingCents: 1100,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(33),
    items: [
      {
        productId: 'seed_prod_008',
        productName: 'Collector Shell Centerpiece',
        quantity: 1,
        priceCents: 17200,
      },
    ],
  },
  {
    id: 'seed_order_009',
    displayOrderId: 'MV-1009',
    createdAt: isoHoursAgo(39),
    totalCents: 8300,
    amountTotalCents: 8300,
    amountSubtotalCents: 7300,
    amountShippingCents: 500,
    amountTaxCents: 500,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'lucas.wright@example.com',
    shippingName: 'Lucas Wright',
    customerName: 'Lucas Wright',
    shippingAddress: {
      name: 'Lucas Wright',
      line1: '520 Marina Dr',
      city: 'Norfolk',
      state: 'VA',
      postal_code: '23510',
      country: 'US',
      phone: '+1 757-555-0182',
    },
    shippingCents: 500,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(37),
    items: [
      {
        productId: 'seed_prod_009',
        productName: 'Sand Dollar Name Card',
        quantity: 4,
        priceCents: 1825,
      },
    ],
  },
  {
    id: 'seed_order_010',
    displayOrderId: 'MV-1010',
    createdAt: isoHoursAgo(46),
    totalCents: 11800,
    amountTotalCents: 11800,
    amountSubtotalCents: 10000,
    amountShippingCents: 900,
    amountTaxCents: 900,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'ella.foster@example.com',
    shippingName: 'Ella Foster',
    customerName: 'Ella Foster',
    shippingAddress: {
      name: 'Ella Foster',
      line1: '16 Salt Marsh Rd',
      city: 'Portland',
      state: 'ME',
      postal_code: '04101',
      country: 'US',
      phone: '+1 207-555-0108',
    },
    shippingCents: 900,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(44),
    items: [
      {
        productId: 'seed_prod_010',
        productName: 'Signature Oyster Keepsake Box',
        quantity: 1,
        priceCents: 10000,
      },
    ],
  },
  {
    id: 'seed_order_011',
    displayOrderId: 'MV-1011',
    createdAt: isoHoursAgo(54),
    totalCents: 9700,
    amountTotalCents: 9700,
    amountSubtotalCents: 8600,
    amountShippingCents: 700,
    amountTaxCents: 400,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'jackson.moore@example.com',
    shippingName: 'Jackson Moore',
    customerName: 'Jackson Moore',
    shippingAddress: {
      name: 'Jackson Moore',
      line1: '72 Wavecrest Ct',
      city: 'San Diego',
      state: 'CA',
      postal_code: '92101',
      country: 'US',
      phone: '+1 619-555-0135',
    },
    shippingCents: 700,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(53),
    items: [
      {
        productId: 'seed_prod_011',
        productName: 'Coastal Ornament Trio',
        quantity: 1,
        priceCents: 8600,
      },
    ],
  },
  {
    id: 'seed_order_012',
    displayOrderId: 'MV-1012',
    createdAt: isoHoursAgo(63),
    totalCents: 13200,
    amountTotalCents: 13200,
    amountSubtotalCents: 11600,
    amountShippingCents: 900,
    amountTaxCents: 700,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'sophia.brooks@example.com',
    shippingName: 'Sophia Brooks',
    customerName: 'Sophia Brooks',
    shippingAddress: {
      name: 'Sophia Brooks',
      line1: '305 Lighthouse Row',
      city: 'Cape May',
      state: 'NJ',
      postal_code: '08204',
      country: 'US',
      phone: '+1 609-555-0166',
    },
    shippingCents: 900,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(62),
    items: [
      {
        productId: 'seed_prod_012',
        productName: 'Wedding Shell Table Marker',
        quantity: 2,
        priceCents: 5800,
      },
    ],
  },
];
