import type { Product } from '../../lib/types';

export const seedAdminProducts: Product[] = [
  {
    id: 'seed_prod_001',
    name: 'Oyster Shell Ring Dish',
    description: 'Signature hand-painted oyster shell ring dish.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-1/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-1/640/640',
    type: 'Keepsakes',
    category: 'Keepsakes',
    categories: ['Keepsakes'],
    oneoff: true,
    quantityAvailable: 3,
    visible: true,
    isSold: false,
    priceCents: 4200,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
  {
    id: 'seed_prod_002',
    name: 'Coastal Trinket Bowl',
    description: 'Soft neutral coastal trinket bowl.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-2/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-2/640/640',
    type: 'Home Decor',
    category: 'Home Decor',
    categories: ['Home Decor'],
    oneoff: true,
    quantityAvailable: 2,
    visible: true,
    isSold: false,
    priceCents: 4800,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
  {
    id: 'seed_prod_003',
    name: 'Pearl Accent Shell Tray',
    description: 'Pearl-accent tray for jewelry and keepsakes.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-3/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-3/640/640',
    type: 'Wedding',
    category: 'Wedding',
    categories: ['Wedding'],
    oneoff: true,
    quantityAvailable: 4,
    visible: true,
    isSold: false,
    priceCents: 8800,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
  {
    id: 'seed_prod_004',
    name: 'Wedding Place Card Shell Set',
    description: 'Set of engraved wedding place card shells.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-4/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-4/640/640',
    type: 'Wedding',
    category: 'Wedding',
    categories: ['Wedding'],
    oneoff: false,
    quantityAvailable: 25,
    visible: true,
    isSold: false,
    priceCents: 10800,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
  {
    id: 'seed_prod_005',
    name: 'Bridal Party Shell Gift Box',
    description: 'Gift-ready box with custom shell keepsake.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-5/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-5/640/640',
    type: 'Gift Sets',
    category: 'Gift Sets',
    categories: ['Gift Sets'],
    oneoff: false,
    quantityAvailable: 10,
    visible: true,
    isSold: false,
    priceCents: 9400,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
  {
    id: 'seed_prod_006',
    name: 'Mini Oyster Ornament',
    description: 'Small ornament with optional personalization.',
    imageUrls: ['https://picsum.photos/seed/demo-prod-6/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-prod-6/640/640',
    type: 'Ornaments',
    category: 'Ornaments',
    categories: ['Ornaments'],
    oneoff: false,
    quantityAvailable: 40,
    visible: true,
    isSold: false,
    priceCents: 2200,
    shippingOverrideEnabled: false,
    shippingOverrideAmountCents: null,
  },
];
