import type { Product } from '../../lib/types';

const soldAt = [
  '2026-02-25T17:22:00.000Z',
  '2026-02-24T14:08:00.000Z',
  '2026-02-23T19:30:00.000Z',
  '2026-02-22T11:12:00.000Z',
  '2026-02-21T09:45:00.000Z',
  '2026-02-20T21:05:00.000Z',
  '2026-02-19T16:18:00.000Z',
  '2026-02-18T12:50:00.000Z',
];

export const seedSoldProducts: Product[] = [
  {
    id: 'seed_sold_001',
    name: 'Pearl Rim Oyster Dish',
    description: 'Hand-finished oyster shell dish with pearl trim.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-1/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-1/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 5400,
    soldAt: soldAt[0],
  },
  {
    id: 'seed_sold_002',
    name: 'Blue Tide Ring Bowl',
    description: 'Coastal blue accented ring bowl.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-2/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-2/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 4800,
    soldAt: soldAt[1],
  },
  {
    id: 'seed_sold_003',
    name: 'Gold Leaf Keepsake',
    description: 'Gold leaf shell keepsake for weddings.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-3/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-3/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 7600,
    soldAt: soldAt[2],
  },
  {
    id: 'seed_sold_004',
    name: 'Satin White Shell Tray',
    description: 'Classic satin white shell tray.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-4/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-4/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 6200,
    soldAt: soldAt[3],
  },
  {
    id: 'seed_sold_005',
    name: 'Monogram Wedding Shell',
    description: 'Monogrammed keepsake shell.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-5/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-5/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 9300,
    soldAt: soldAt[4],
  },
  {
    id: 'seed_sold_006',
    name: 'Driftwood Accent Dish',
    description: 'Natural shell with driftwood accent paint.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-6/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-6/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 5100,
    soldAt: soldAt[5],
  },
  {
    id: 'seed_sold_007',
    name: 'Champagne Edge Ornament',
    description: 'Holiday shell ornament with champagne edge.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-7/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-7/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 4600,
    soldAt: soldAt[6],
  },
  {
    id: 'seed_sold_008',
    name: 'Collector Coastal Centerpiece',
    description: 'Large collector centerpiece shell.',
    imageUrls: ['https://picsum.photos/seed/demo-sold-8/640/640'],
    imageUrl: 'https://picsum.photos/seed/demo-sold-8/640/640',
    type: 'Sold',
    oneoff: true,
    quantityAvailable: 0,
    visible: false,
    isSold: true,
    priceCents: 12800,
    soldAt: soldAt[7],
  },
];
